/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_study_jvm_JvmCompilation */

#ifndef _Included_com_study_jvm_JvmCompilation
#define _Included_com_study_jvm_JvmCompilation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_study_jvm_JvmCompilation
 * Method:    simpleFieldNative
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_study_jvm_JvmCompilation_simpleFieldNative
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
